name: test-centos7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: "Run pytest on centos7"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          registry: quay.io
          image: centos:7
          options: -v ${{ github.workspace }}:/work
          run: |
            curl --silent -OJL  https://github.com/indygreg/python-build-standalone/releases/download/20240107/cpython-3.12.1+20240107-x86_64-unknown-linux-gnu-install_only.tar.gz
            tar xzf cpython-3.12.1+20240107-x86_64-unknown-linux-gnu-install_only.tar.gz
            cd /work
            /python/bin/python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.lock -r requirements-dev.lock
            pytest

