---
name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release_to_pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/coverage-sh/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
      - name: Build
        run: |
          rye build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450
        with:
          repository-url: https://test.pypi.org/legacy/