name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write

jobs:
  release_to_pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    #    environment:
    #      name: pypi
    #      url: https://pypi.org/p/coverage-sh/

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          version: '0.29.0'
      - name: build
        run: |
          rye build --wheel
      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
